# This is a generated file. Not intended for manual editing.
services:
  ecommerceapp:
    build:
      context: "/Users/dimplesingh/github/EShop_WebAPI.NET/ECommerceApp"
      dockerfile: "ECommerceApp/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/ECommerceApp.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "ecommerceapp:dev"
    ports: []
    volumes:
    - "/Users/dimplesingh/github/EShop_WebAPI.NET/ECommerceApp/ECommerceApp:/app:rw"
    - "/Users/dimplesingh/github/EShop_WebAPI.NET/ECommerceApp:/src:rw"
    - "/Users/dimplesingh/.nuget/packages:/home/app/.nuget/packages"
    working_dir: "/app"
